name: Build ESPHome

on:
  push:
    paths:
      - '**.yaml'
  pull_request:
    paths:
      - '**.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: esphome/actions/build@v1
        with:
          configs: water-flow-sensor.yaml